"""Changes schema

Revision ID: cce8ac53e631
Revises: fc276d2cc657
Create Date: 2018-09-13 13:03:23.135200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce8ac53e631'
down_revision = 'fc276d2cc657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    op.drop_table('dislike')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislike',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dislike', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitch.id'], name='dislike_pitch_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='dislike_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dislike_pkey')
    )
    op.create_table('like',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('like', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitch.id'], name='like_pitch_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='like_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='like_pkey')
    )
    # ### end Alembic commands ###
